apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth
  namespace: monitoring
type: Opaque
data:
  admin-user: YWRtaW4=   # "admin" encodé en base64
  admin-password: YWRtaW4=   # "admin" encodé en base64
